import { fmtInr, formatInvoiceDate } from '@/lib/gst';

export type EwayBillSheetData = {
  ewbNo: string;
  ewbDate: string;
  validUpto?: string | null;
  transportMode: string;
  distanceKm?: number | null;
  vehicleNo?: string | null;
  transporterId?: string | null;
  transporterName?: string | null;
  transporterDocNo?: string | null;
  transporterDocDate?: string | null;
};

/** Printed page 2 — only rendered once an e-Way Bill has actually been
 * generated (see Invoice.ewbNo). Forced onto its own page by `.eway-page`'s
 * `break-before: page` rule in globals.css, right after invoice-sheet-classic's
 * page 1 inside the same `.invoice-print` container. Mirrors the standard
 * NIC e-Way Bill printout: From/To (brief) separate from Dispatch-From/
 * Ship-To (full address), a goods table by HSN, and Transportation/Vehicle
 * detail sections. */
export function InvoiceEwayBillSheet({
  eway,
  invoiceNumber,
  invoiceDate,
  irn,
  qrImageDataUrl,
  fromCompany,
  toCustomer,
  taxableValue,
  cgst,
  sgst,
  igst,
  roundOff,
  total,
  useIgst,
  gstRateLabel,
  hsnGoods,
}: {
  eway: EwayBillSheetData;
  invoiceNumber: string;
  invoiceDate: string;
  irn?: string | null;
  qrImageDataUrl?: string | null;
  fromCompany: { name: string; gstin?: string | null; address?: string | null; state: string; pincode?: string | null; district?: string | null };
  toCustomer: { name: string; gstin?: string | null; address?: string | null; state: string; pincode?: string | null };
  taxableValue: number;
  cgst: number;
  sgst: number;
  igst: number;
  roundOff: number;
  total: number;
  useIgst: boolean;
  /** e.g. "2.50+2.50" (CGST+SGST) or "18.00" (IGST) — matches the NIC
   * printout's "Tax Rate (C+S)" column convention. */
  gstRateLabel: string;
  hsnGoods: { hsn: string; description: string; qty: string; taxableValue: number }[];
}) {
  return (
    <div className="eway-page rounded-lg2 border border-ink bg-white p-6 text-[12px] leading-normal text-ink-body">
      <div className="flex items-start justify-between border-b border-ink pb-3">
        <div>
          <div className="text-[14.5px] font-extrabold uppercase tracking-wide text-ink">e-Way Bill</div>
          <div className="mt-1.5 text-[10.5px] text-ink-faint">
            Doc No. : Tax Invoice - {invoiceNumber}
            <br />
            Date : {formatInvoiceDate(invoiceDate)}
          </div>
          {irn && <div className="mt-1 max-w-[420px] break-all font-mono text-[9.5px] text-ink-faint">IRN : {irn}</div>}
        </div>
        {qrImageDataUrl && (
          <div className="text-right">
            <div className="text-[9px] font-bold uppercase tracking-wide text-ink-faint">e-Way Bill</div>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={qrImageDataUrl} alt="e-Invoice QR" className="ml-auto h-[90px] w-[90px]" />
          </div>
        )}
      </div>

      <table className="w-full border-collapse text-[11.5px]">
        <tbody>
          <tr>
            <td className="w-1/2 border border-ink bg-surface-alt p-3 align-top">
              <div className="mb-1.5 font-bold">1. e-Way Bill Details</div>
              <Row k="e-Way Bill No." v={eway.ewbNo} />
              <Row k="Generated Date" v={formatInvoiceDate(eway.ewbDate)} />
              {eway.validUpto && <Row k="Valid Upto" v={formatInvoiceDate(eway.validUpto)} />}
              <Row k="Mode" v={eway.transportMode} />
              {eway.distanceKm != null && <Row k="Approx Distance" v={`${eway.distanceKm} KM`} />}
            </td>
            <td className="w-1/2 border border-ink bg-surface-alt p-3 align-top">
              <div className="mb-1.5 font-bold">2. Generated By</div>
              <Row k="Generated By" v={fromCompany.gstin || '—'} />
              <Row k="Supply Type" v="Outward-Supply" />
              <Row k="Transaction Type" v="Regular" />
            </td>
          </tr>
          <tr>
            <td className="border border-ink p-3 align-top">
              <div className="mb-1.5 font-bold">From</div>
              <div className="font-bold text-ink">{fromCompany.name}</div>
              {fromCompany.gstin && <div className="font-mono font-tabular">GSTIN : {fromCompany.gstin}</div>}
              <div>{fromCompany.state}</div>
            </td>
            <td className="border border-ink p-3 align-top">
              <div className="mb-1.5 font-bold">To</div>
              <div className="font-bold text-ink">{toCustomer.name}</div>
              {toCustomer.gstin && <div className="font-mono font-tabular">GSTIN : {toCustomer.gstin}</div>}
              <div>{toCustomer.state}</div>
            </td>
          </tr>
          <tr>
            <td className="border border-ink p-3 align-top">
              <div className="mb-1.5 font-bold">Dispatch From</div>
              {fromCompany.address && <div className="whitespace-pre-line leading-relaxed">{fromCompany.address}</div>}
              <div>
                {fromCompany.state}
                {fromCompany.pincode ? ` ${fromCompany.pincode}` : ''}
              </div>
            </td>
            <td className="border border-ink p-3 align-top">
              <div className="mb-1.5 font-bold">Ship To</div>
              {toCustomer.address && <div className="whitespace-pre-line leading-relaxed">{toCustomer.address}</div>}
              <div>
                {toCustomer.state}
                {toCustomer.pincode ? ` ${toCustomer.pincode}` : ''}
              </div>
            </td>
          </tr>
        </tbody>
      </table>

      <div className="mt-3 mb-1.5 text-[11.5px] font-bold">3. Goods Details</div>
      <table className="w-full border-collapse text-[11.5px]">
        <thead>
          <tr className="border border-ink bg-surface-alt text-left font-bold">
            <th className="border-r border-ink px-2.5 py-1.5">HSN Code</th>
            <th className="border-r border-ink px-2.5 py-1.5">Product Name &amp; Desc</th>
            <th className="border-r border-ink px-2.5 py-1.5 text-right">Quantity</th>
            <th className="border-r border-ink px-2.5 py-1.5 text-right">Taxable Amt</th>
            <th className="px-2.5 py-1.5 text-right">Tax Rate (C+S)</th>
          </tr>
        </thead>
        <tbody>
          {hsnGoods.map((g) => (
            <tr key={g.hsn} className="border-b border-line">
              <td className="border-r border-ink px-2.5 py-1.5 font-mono">{g.hsn}</td>
              <td className="border-r border-ink px-2.5 py-1.5">{g.description}</td>
              <td className="border-r border-ink px-2.5 py-1.5 text-right font-mono font-tabular">{g.qty}</td>
              <td className="border-r border-ink px-2.5 py-1.5 text-right font-mono font-tabular">{fmtInr(g.taxableValue)}</td>
              <td className="px-2.5 py-1.5 text-right font-mono font-tabular">{gstRateLabel}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-3 flex flex-wrap justify-between gap-x-6 border-t border-ink pt-2.5 text-[11.5px]">
        <span>
          Tot.Taxable Amt : <b className="font-mono font-tabular">{fmtInr(taxableValue)}</b>
        </span>
        <span>
          Other Amt : <b className="font-mono font-tabular">{fmtInr(roundOff)}</b>
        </span>
        <span>
          Total Inv Amt : <b className="font-mono font-tabular">{fmtInr(total)}</b>
        </span>
      </div>
      <div className="mt-1.5 flex flex-wrap gap-x-6 text-[11.5px]">
        {useIgst ? (
          <span>
            IGST Amt : <b className="font-mono font-tabular">{fmtInr(igst)}</b>
          </span>
        ) : (
          <>
            <span>
              CGST Amt : <b className="font-mono font-tabular">{fmtInr(cgst)}</b>
            </span>
            <span>
              SGST Amt : <b className="font-mono font-tabular">{fmtInr(sgst)}</b>
            </span>
          </>
        )}
      </div>

      <div className="mt-3.5 border-t border-ink pt-2.5 text-[11.5px] font-bold">4. Transportation Details</div>
      <Row k="Transporter ID" v={eway.transporterId || '—'} />
      <Row k="Name" v={eway.transporterName || '—'} />
      <Row k="Doc No." v={eway.transporterDocNo || '—'} />
      <Row k="Date" v={eway.transporterDocDate ? formatInvoiceDate(eway.transporterDocDate) : '—'} />

      <div className="mt-2.5 border-t border-ink pt-2.5 text-[11.5px] font-bold">5. Vehicle Details</div>
      <Row k="Vehicle No." v={eway.vehicleNo || '—'} />
      <Row k="From" v={fromCompany.district || fromCompany.state} />
    </div>
  );
}

function Row({ k, v }: { k: string; v: string }) {
  return (
    <div className="flex justify-between gap-2 py-[3px]">
      <span className="text-ink-faint">{k}</span>
      <span className="font-mono font-tabular">{v}</span>
    </div>
  );
}
